spring.application.name=ecommerce
server.port=9092

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Karthik1005
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

